# Generated by Django 4.2.7 on 2025-10-02 04:43

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_image_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_main', 'id'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Описание изображения для SEO и доступности', max_length=255, verbose_name='Альтернативный текст'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Форматы: JPEG, PNG, WebP. Размер: 400×300 - 3000×3000 пикселей. Максимум: 5 МБ', upload_to='products/', validators=[catalog.models.validate_image_size, catalog.models.validate_image_dimensions], verbose_name='Изображение'),
        ),
    ]
