# Generated by Django 4.2.7 on 2025-10-02 07:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productimage_options_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Используйте форматирование для создания таблиц, списков и выделения текста', verbose_name='Описание'),
        ),
    ]
