# Generated by Django 4.2.7 on 2025-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', 'sort_order', 'name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Будет показан в начале списка', verbose_name='Рекомендуемый товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Чем меньше число, тем выше товар в списке', verbose_name='Порядок сортировки'),
        ),
    ]
