# Generated by Django 4.2.7 on 2025-10-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
    ]
